#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri May 23 00:49:43 EDT 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=32
shaderPack=BSL_v8.4.02.2.zip
